"""initial schema: products, coupons, resellers, orders

Revision ID: 0001
Revises:
Create Date: 2026-06-01

Hand-written (not autogenerated) so the enum types, CHECK constraints, the
partial index, and the UNIQUE(product_id) safety net are all explicit and
reviewable.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    bind = op.get_bind()

    # Create enum types up front (create_type=False on the columns below so the
    # table creation doesn't try to create them a second time).
    product_type = postgresql.ENUM("COUPON", name="product_type")
    coupon_value_type = postgresql.ENUM("STRING", "IMAGE", name="coupon_value_type")
    order_channel = postgresql.ENUM("DIRECT", "RESELLER", name="order_channel")
    product_type.create(bind, checkfirst=True)
    coupon_value_type.create(bind, checkfirst=True)
    order_channel.create(bind, checkfirst=True)

    op.create_table(
        "products",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column(
            "type",
            postgresql.ENUM("COUPON", name="product_type", create_type=False),
            nullable=False,
        ),
        sa.Column("image_url", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    )

    op.create_table(
        "coupons",
        sa.Column(
            "product_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("products.id", ondelete="CASCADE"),
            primary_key=True,
        ),
        sa.Column("cost_price", sa.Numeric(12, 2), nullable=False),
        sa.Column("margin_percentage", sa.Numeric(6, 2), nullable=False),
        sa.Column("minimum_sell_price", sa.Numeric(12, 2), nullable=False),
        sa.Column("is_sold", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "value_type",
            postgresql.ENUM("STRING", "IMAGE", name="coupon_value_type", create_type=False),
            nullable=False,
        ),
        sa.Column("value", sa.String(), nullable=False),
        sa.CheckConstraint("cost_price >= 0", name="ck_coupons_cost_price_nonneg"),
        sa.CheckConstraint("margin_percentage >= 0", name="ck_coupons_margin_nonneg"),
        sa.CheckConstraint("minimum_sell_price >= 0", name="ck_coupons_min_sell_nonneg"),
    )
    op.create_index(
        "ix_coupons_unsold", "coupons", ["is_sold"], postgresql_where=sa.text("is_sold = false")
    )

    op.create_table(
        "resellers",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.UniqueConstraint("token_hash", name="uq_resellers_token_hash"),
    )

    op.create_table(
        "orders",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "product_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("products.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column(
            "channel",
            postgresql.ENUM("DIRECT", "RESELLER", name="order_channel", create_type=False),
            nullable=False,
        ),
        sa.Column(
            "reseller_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("resellers.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("final_price", sa.Numeric(12, 2), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        # One sale per product, enforced by the database.
        sa.UniqueConstraint("product_id", name="uq_orders_product_id"),
    )


def downgrade() -> None:
    op.drop_table("orders")
    op.drop_table("resellers")
    op.drop_index("ix_coupons_unsold", table_name="coupons")
    op.drop_table("coupons")
    op.drop_table("products")
    for enum_name in ("order_channel", "coupon_value_type", "product_type"):
        postgresql.ENUM(name=enum_name).drop(op.get_bind(), checkfirst=True)
